### ISSUE TITLE
Custom Congestion Control does not work

### ISSUE THREAD

**Issue by debopambhattacherjee** [dorkbox/Network#1]
I extend the default congestion control as follows:
public class Test extends CCC{
public Test(){
System.out.println("I am here!");
}
public void setCwnd(int win){
setCWndSize(win);
}
}

I set the customized CC for the SocketUDT instance as follows:
SocketUDT socket = new SocketUDT(TypeUDT.STREAM);
socket.setOption(OptionUDT.UDT_CC, new FactoryUDT(PCC.class));
socket.connect(new InetSocketAddress("127.0.0.1", 5555));
Object obj = socket.getOption(OptionUDT.UDT_CC);
Test test = (Test) obj;
test.setCwnd(1200);

The point is after this instant the congestion window remains fixed at 1200. I transfer huge files but the window does not change. The expected behavior here is that the default congestion control works as usual as I have not overridden any of the superclass methods. Let me know if this is a bug or I am getting something wrong here. Thank you.

**Comment by dorkbox** [comment]
(wow.. I just now got to this. I was traveling in July and completely missed this issue. My apologies...)

It turns out that the UDT java/C bridge implementation is buggy and didn't work very well. Straight-up TCP was faster (via Java), unless it was in C, and then the speed improvements are massive. 

Because of this, the UDT library has been marked for removal upstream -- and so I've removed it as well. 

I still maintain the UDT C implementation.
